name: Build and Deploy
on: [push]
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: marp-gh-page
        uses: timo-reymann/marp-gh-page-action@v2
        with:
          domain: public-money-public-code.slides.timo-reymann.de
          assets_path: images
